//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR7
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        public int order_id { get; set; }
        public int part_id { get; set; }
        public int count { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<int> delivery_progress { get; set; }
        public Nullable<bool> id_delivered { get; set; }
    
        public virtual AutoParts AutoParts { get; set; }
    }
}
