//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int IdWarehouse { get; set; }
        public int IdPart { get; set; }
        public int Count { get; set; }
        public decimal Balance { get; set; }
    
        public virtual AutoParts AutoParts { get; set; }
    }
}
